// <auto-generated />
using DearDiaryLogs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DearDiaryLogs.Migrations
{
    [DbContext(typeof(DearDiaryLogsContext))]
    partial class DearDiaryLogsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("DearDiaryLogs.Models.DiaryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EndTime");

                    b.Property<string>("EventName");

                    b.Property<string>("Height");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("StartTime");

                    b.Property<string>("StoryUrl");

                    b.Property<string>("Width");

                    b.HasKey("Id");

                    b.ToTable("DiaryLog");
                });
#pragma warning restore 612, 618
        }
    }
}
